### PR TITLE
Typo fix in app service API specs

### PR DESCRIPTION
**Pull request by jooola**
Typo fix Massaging -> Messaging  in app service API specs

### CODE REVIEW

**Comment by turt2live** [comment]
It is actually "massaging", but thank you!

**Comment by rubo77** [comment]
Why was this closed

**Comment by t3chguy** [comment]
Because it isn't a typo

**Comment by richvdh** [comment]
given that we seem to get repeated PRs for this, it's clear that people aren't understanding the intended meaning... we should probably rephrase...

**Comment by richvdh** [comment]
s/massaging/manipulation/ maybe?

**Comment by turt2live** [comment]
I'm not sure a spike in activity means we're obligated to look at it. It is a poor name, but it's also been called this for years. An issue to track it would be better than comments on a closed PR.

**Pull request closed without merging**
