### PR TITLE
Preposal for /sync response changes.

### PR DESCRIPTION
**Pull request by richvdh**
- get rid of the 'event_map' and put the events directly in the timeline or state
- rename the children of the 'rooms' dict from "joined/invited/archived" to "join/invite/leave" to match the membership states
- ~~move the contents of the 'unsigned' dictionary into the events themselves~~ (now reverted)
- ~~replace the state list with two layers of dictionary keyed on type and state_key~~ (now reverted)

I think this should be fairly uncontroversial now.

### CODE REVIEW

**Comment by richvdh** [comment]
@erikjohnston could you have first look at this?

**Comment by richvdh** [comment]
Having implemented it, and tried to use it, I can say I'm not at all in favour of changing `state` to a dict of dicts. It's a pain to use on the client side, as (1) you are never going to be able to just dump it in over the existing state, thanks to the need to intelligently merge dicts, and (2) you have to write the code twice: once to work on a list in the timeline, and once on a dict-of-dicts in the state.

**Comment by richvdh** [comment]
We've been through the pros and cons of flattening `unsigned` into the main event object, and the summary is basically as follows:

On the up side, it gives an aesthetically cleaner and more intuitive client-server API; it is easier for client developers to remember "the `age` key gives the age of the event" than it is "the `unsigned.age` key gives the age of the event".

On the down side, we would have to specify what we do in the case of key clashes between the event body and the `unsigned` object. There are a few options:
* Give up all pretence at a correlation between events in the federation API and those in the client-server API, and instead give a list list of the event keys for the C-S API and where they should come from. There are problems with this:
 * Increases complexity in the specification and server implementation (with no real corresponding reduction in complexity elsewhere)
 * Makes it impossible to add extensions (whereby clients or servers can add keys to events) outwith the spec.
 * In future, we want to allow clients to get the complete federated event, so that they can validate its signature themselves. This would mean that clients would have to be able to handle a completely different format of event in this situation.
* Allow a flattening to take place, but specify that signed keys take precedence over unsigned ones, or vice-versa. But it's unclear what the semantics of this would be. And it doesn't really do much to improve the C-S API: "age is the age of the event, unless it was set to a different value by the originating client, in which case it is that value"
* Avoid the issue by having a list of `signed_keys` instead of an `unsigned` subobject in the federation API. The issue of a clash could never then occur, but this would introduce complexity into the server implementation: you would have to remember to check that any key you cared about had been signed. This will be easy to get wrong; given that this is security-related, that is not good.

**Comment by richvdh** [comment]
I think this is more-or-less trivial now. I want to wrap it up, so @NegativeMjark / @erikjohnston / @Kegsay / @illicitonion unless you have any objections I'll merge it later today.

**Comment by erikjohnston** [comment]
This works for me.

If we have people in the wild actually get confused and annoyed by `unsigned` we can revisit the decision.

**Pull request merged**
