### PR TITLE
Tempering the sales pitch of puppetted bridges.

### PR DESCRIPTION
**Pull request by kfatehi**
Folks are getting confused. The article sells the puppeted bridge
concept a little too hard and needs to temper it with the reality that
most networks people want to bridge (Facebook, Hangouts) suffer from the
fact that there is no means of representation for non-puppeted users.

Relevant discussions:

* https://matrix.to/#/!ChuQQIVJvwyJujhNIG:synapse.keyvan.pw/$149063160814JjbEL:gruenhage.xyz
* https://matrix.to/#/!svJUttHBtRMdXmEhEy:matrix.org/$149072185910105qOwCB:synapse.keyvan.pw

Signed-off-by: Keyvan Fatehi <keyvanfatehi@gmail.com>

### CODE REVIEW

**Comment by kfatehi** [comment]
Don't merge. this is an ongoing discussion

**Comment by kfatehi** [comment]
LeoNerd
Yah I'd avoid the wording about hangouts to facebook there. It's unnecessarily complicated - without a relaybot on Hangouts, say, such a bridge still can't represent other Matrix users
L
10:58
Imean, your point is correct, but a simpler situation is also correct

kfatehi (@kfatehi:synapse.keyvan.pw)
oh yeah good point. the facebook<->hangouts helped me to understand what jcgruenhage wanted when he started this discussion, so i used it in the doc there. but i totally didn't address that we can't address other real matrix users.

**Comment by leonerd** [comment]
It's probably worth also adding a section into the doc about hybrid relaybot+puppet bridges, a.la. current `matrix-appservice-gitter`, because that's a useful case that isn't so far discussed here.

**Comment by kfatehi** [comment]
I've done what I set out to do in this PR, if anyone would like to review for merge. Thanks

**Comment by ara4n** [comment]
thanks - lgtm!

**Pull request merged**
