### PR TITLE
Comment out the timestamp massaging section for now

### PR DESCRIPTION
**Pull request by turt2live**
Rendered: see 'docs' status check

----

Pending discussion on https://github.com/matrix-org/matrix-doc/issues/1585

### CODE REVIEW

**Comment by Half-Shot** [comment]
So we are officially taking this feature out for r0?

**Comment by turt2live** [comment]
Yup. It needs a lot of thought and planning, which means it really should go through a full review cycle. There's no evidence that the API is used in practice beyond experiments from people, however Synapse is likely to maintain support for the feature in the meantime (as a Synapse feature rather than a spec feature).

**Comment by Half-Shot** [comment]
>Yup. It needs a lot of thought and planning, which means it really should go through a full review cycle. There's no evidence that the API is used in practice beyond experiments from people, however Synapse is likely to maintain support for the feature in the meantime (as a Synapse feature rather than a spec feature).

This is all fine, but I'd like a tombstone notice to let people know that it's no longer a thing as far as r0 is concerned when people go looking for it.

**Comment by turt2live** [comment]
apparently I forgot to actually add you as a reviewer - thank you in any case!

**Pull request merged**
