### PR TITLE
Fix for the #1865

### PR DESCRIPTION
**Pull request by ma1uta**
Add the m.push_rules schema.

It needs to check carefully the schema.

Signed-off-by: Anatoly Sablin  sablintolya@gmail.com

### CODE REVIEW

**Comment by turt2live** [comment]
Using `$ref` at every available opportunity is the best deduplication approach. PDUs in the s2s spec are a great example of this.

**Comment by richvdh** [comment]
Ah yes. there are plenty of examples of APIs which refer to event schemas.

@ma1uta: could you rework this to remove the duplication?

**Comment by ma1uta** [comment]
@richvdh done.

**Comment by turt2live** [comment]
A changelog (clarification) and this is ready to merge, I guess :)

**Comment by ma1uta** [comment]
@richvdh @turt2live @KitsuneRal done. I hope this is enough to merge :)

**Comment by turt2live** [comment]
Lots of green checkmarks compels me to merge this. Thanks for the PR!

**Pull request merged**
