### PR TITLE
Document convention of using underscores in APIs

### PR DESCRIPTION
**Pull request by richvdh**
Everybody has agreed to it. Now we just have to remember to do it.

### CODE REVIEW

**Comment by Kegsay** [comment]
Given that all(?) the JSON keys are also `with_underscores`, might it be an idea to cement that at the same time?

**Comment by richvdh** [comment]
@Kegsay: ptal?

**Comment by richvdh** [comment]
`displayname` and `display_name` seem about as common as each other :(

**Comment by Kegsay** [comment]
LGTM

**Pull request merged**
