### PR TITLE
Don't mark 'aliases' on m.room.canonical_alias as required

### PR DESCRIPTION
**Pull request by leonerd**

### CODE REVIEW

**Comment by Kegsay** [comment]
The key is called `alias` not `aliases`. Under what circumstances will you get a canonical alias event which doesn't specify a canonical alias? If you remove it, should it be `null` or missing entirely?

**Comment by erikjohnston** [comment]
@Kegsay: Redactions

**Comment by erikjohnston** [comment]
Its also a handy way of clearing the canonical alias of a room

**Comment by erikjohnston** [comment]
Oh, err, LGTM

**Pull request merged**
