### PR TITLE
MSC2472: Symmetric SSSS

### PR DESCRIPTION
**Pull request by uhoreg**
[Rendered](https://github.com/uhoreg/matrix-doc/blob/symmetric_ssss/proposals/2472-symmetric-ssss.md)

### CODE REVIEW

**Comment by auscompgeek** [comment]
Were AEAD modes such as GCM considered?

**Comment by uhoreg** [comment]
I believe GCM was considered earlier when e2ee was originally being implemented, but there was lack of support in some libraries.  It may be better supported now, but I'd rather not add another encryption mode to the mix (we already use CBC and CTR), and stick with things that we're already using where possible.  In the future, we may at some point do a bulk review of the encryption that we use and switch things across the board at that time, but for now, I think it's better to stay with things that we already use.

**Comment by ara4n** [comment]
this lgtm; i'd suggest proposing a merge tbh.

**Comment by turt2live** [comment]
@mscbot fcp merge

**Comment by dbkr** [comment]
Updating the 1946 proposal to say the same thing seems quite confusing - I'd have probably either left it in and marked it as superseded or deleted it rather than have duplicated content.

Looks fine otherwise though.

**Comment by anoadragon453** [comment]
Agree as well that copying the contents and modifying them in this MSC and putting a "superseded" warning in the old MSC would've been clearer, but oh well.

We should link the implementations of this, though that may be a lot of different PRs. Instead, I'll just mention that this has been implemented in Riot Web ([riot-web](https://github.com/vector-im/riot-web/), [matrix-react-sdk](https://github.com/matrix-org/matrix-react-sdk/), [matrix-js-sdk](https://github.com/matrix-org/matrix-js-sdk/)), [RiotX Android](https://github.com/vector-im/riotX-android/) and [Riot iOS](https://github.com/vector-im/riot-ios/).

**Comment by uhoreg** [comment]
I've made a couple of update:
- keys don't need to be signed any more since they're trusted on the basis of us having the secret key (this was only necessary when using an asymmetric algorithm)
- added some information so that we can check the key before we try to use it

As far as modifying the text of the original MSC, I'm not sure what's the best way to do it, and am open to suggestions.  I think that all approaches have some sort of downside.  I wanted to do it in a way that there was one document that people could look at to get the current recommendation, and to have something explaining the rationale behind the change.

**Comment by uhoreg** [comment]
Implemented in Riot-web by https://github.com/matrix-org/matrix-js-sdk/pull/1238 and https://github.com/matrix-org/matrix-js-sdk/pull/1294

@ara4n can you convert your "lgtm" to a :heavy_check_mark: ?

**Comment by richvdh** [comment]
seems entirely plausible to me. I'm assuming that other people have thought about the crypto aspects of this.

**Comment by turt2live** [comment]
Somehow this missed the list of things that passed FCP

**Comment by uhoreg** [comment]
Merged! :tada:

**Comment by richvdh** [comment]
> Updating the 1946 proposal to say the same thing seems quite confusing - I'd have probably either left it in and marked it as superseded or deleted it rather than have duplicated content.

Coming back here three years later: +1 to this. It confused me greatly: let's not do that again. Or if we do, let's at least leave a note on the original PR to say what happened. (Now done for MSC1946.)

**Pull request merged**
