### PR TITLE
Add GeoJSON & accuracy to m.location.

### PR DESCRIPTION
**Pull request by Half-Shot**

### CODE REVIEW

**Comment by Half-Shot** [comment]
cc @ara4n @Ralith

**Comment by Ralith** [comment]
It's unclear what "accuracy" means, exactly. "5 meters of accuracy" doesn't mean anything on its own. For it to be useful in practice, it should probably either be given a clear statistical definition.

**Comment by Half-Shot** [comment]
(note to self to rethink this one)

Also, one thing that would be nice is descriptive locations e.g. being able to tell the client whether it is the user's present location, or a static marker on a map.

**Comment by NotAFile** [comment]
> It's unclear what "accuracy" means, exactly. "5 meters of accuracy" doesn't mean anything on its own. For it to be useful in practice, it should probably be given a clear statistical definition.

The usual defintion here for GPS is "CEP": the size of the circle in which at least 50% of the measurements land.

**Comment by turt2live** [comment]
I'm closing this in favour of an MSC, sorry. Thanks for the PR @Half-Shot, though I think it was before its time :(

**Pull request closed without merging**
