### PR TITLE
spec two new error types

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/matrix-org/matrix-doc/issues/1254
Fixes https://github.com/matrix-org/matrix-doc/issues/1252

### CODE REVIEW

**Comment by maxidor** [comment]
What is the related spec proposal for this?

**Comment by turt2live** [comment]
This is small enough that this can qualify as a proposal imho.

**Comment by maxidor** [comment]
The PR doesn't explain why this is even a thing, so I respectfully disagree. It really ought to be explained properly.

**Comment by Half-Shot** [comment]
I concur with Travis here. Especially as it's literally a dictionary of errors that you don't need to send if you don't implement.

**Comment by non-Jedi** [comment]
Both of these errors are related to the work done to satisfy GDPR and should be included in a spec proposal for that work as I stated in #1290.

**Comment by turt2live** [comment]
just for keeping the record updated: after further review I agree: a larger GDPR proposal should be required.

**Comment by richvdh** [comment]
ok let's close this for now pending a GDPR spec.

**Pull request closed without merging**
