### PR TITLE
Remove mclient.el from the Projects page

### PR DESCRIPTION
**Pull request by rrix**
I'm removing this from MELPA since it's buggy, unmaintained, doesn't work with e2e and I don't have
bandwidth to fix it right now. :(

### CODE REVIEW

**Comment by rrix** [comment]
thanks matrixbot; i'm not sure if the index is auto-generated or not, so

**Comment by ara4n** [comment]
we're looking at fixing e2e by providing a proxy that folks can run clientside for clients like this. how bad is the buggy-ness, ooi? seems a shame to hide it :(

**Comment by rrix** [comment]
@ara4n the problem is that when the HTTP library does any callbacks it swallows up exceptions, which means that if it breaks, it does so silently, and until I can figure out how to make it ... not do that, it makes sense to not support it. I'm at a spot in life right now where I don't have the bandwidth to make this work well enough for people to have a good experience using Matrix, and so in my and the project's best interest, it makes sense to minimize its impact for now. It's still on my Gogs instance if people want to use it directly, and I plan to write a "postmortem" on it for soemone to know where to start picking up if they want to work on it while I am unable to do so.

**Comment by ara4n** [comment]
ok.

**Pull request merged**
