### PR TITLE
Add index page

### PR DESCRIPTION
**Pull request by illicitonion**

### CODE REVIEW

**Comment by ara4n** [comment]
wfm, although it is still unclear what version the index & intro has, if any.

**Comment by illicitonion** [comment]
They are consciously unversioned; if we feel we need to start versioning our thing telling people what versions things are, we can cross that bridge.

**Comment by ara4n** [comment]
if they are consciously unversioned, please make that explicit to avoid other people asking the Q

**Comment by illicitonion** [comment]
Pushed 53a21fc to mention why not versioned

**Comment by ara4n** [comment]
thanks. final request (and sorry for missing this during the review): please can we link to the intro *before* the API sections, not after it.  I.e.:

 * Intro
 * CS API
 * SS API
 * AS API
 * Appendixes

As obviously Intro is the first thing we want people to see & read.

**Pull request merged**
