### PR TITLE
Updating login endpoint spec to match new identifier format

### PR DESCRIPTION
**Pull request by maxidor**
Followed @richvdh [recommendation to fix spec](https://matrix.to/#/!fILrmqIZQfJcrUiBRk:matrix.org/$1508947210656wSEEv:sw1v.org) for next iteration

Signed-off-by: Max Dor @ Kamax.io (no email to avoid spam)

### CODE REVIEW

**Comment by maxidor** [comment]
Signed-off-by: Maxime Dor @ Kamax.io (no email to avoid spam)

**Comment by maxidor** [comment]
@richvdh What can I do or who can I ping to move this forward?

**Comment by richvdh** [comment]
oh, me.

Thanks very much for looking at this. I'll take a look soon but spec work has taken up a lot of time this week and I need to get some other code written to meet a deadline.

**Comment by richvdh** [comment]
@matrixbot: test this please

**Comment by richvdh** [comment]
Sadly I think we're going to have to document the old format as something that servers have to support *as well* :/.

Also: please could you add a changelog entry?

**Comment by maxidor** [comment]
@richvdh not sure I follow: do you want me to redo this PR to include the old format (which was never used AFAIK) and the new format side-by-side? This PR is about documenting the existing behavior, so I would just close it if that's not acceptable.

**Comment by richvdh** [comment]
The old format was used by Riot for a long time, and is still used by other clients (for example, libqmatrixclient uses it). It still works fine for the case of email identifiers; of course for other identifiers you need to use the format.

One of the principles behind the C-S versioning scheme is that we try hard to avoid changes that are going to break clients. The C-S Spec is the thing that documents what we expect servers to support, and in short I expect servers claiming to implement the r0 api to support the old format - though we can certainly flag it as deprecated as far as clients are concerned.

So: yes I'd like you to include both the new and old format. I'm not exactly sure what form that ought to take - it doesn't *necessarily* need to combine both together, provided the spec ends up documenting the old format as well as the new one so that servers can support clients like libqmatrixclient.

**Comment by maxidor** [comment]
Ah I see, totally missed that part. I'll think of a way to combine both, provide a commit and get back to you for review!

**Comment by maxidor** [comment]
As I'm focusing on documenting the current behavior, I'll close this for now and revisit later.
FYI, as-is code has been added into https://github.com/eventually-matrix/matrix-doc/commit/c07be4487b54a5dbde7feb1fb9d8c9a690e9327f instead.

**Pull request closed without merging**
