### PR TITLE
Suggested Mentions Proposal

### PR DESCRIPTION
**Pull request by Half-Shot**
[Rendered](https://github.com/Half-Shot/matrix-doc/blob/hs/suggested-mentions/proposals/1488-suggested-mentions.md)

### CODE REVIEW

**Comment by turt2live** [comment]
Out of interest, why not take inspiration from extensible events and include some sort of "ping these people" list? It would probably need some sanity checking like the user consenting to random keywords and ensuring that someone doesn't list the entire room in there.

The approach could be (not fully thought out, just a very rough idea):
```
"body": "Hello AReallyLo!",
"m.mentions": {
  "AReallyLo": "@areallylongname:matrix.org"
}
```

Also gives the opportunity for fancier pills, etc in clients.

**Comment by Half-Shot** [comment]
Yeah, that's not a bad option. We could include a "m.mentions" in regular messages and then mod synapse/riot-(web|android|ios) to support it.

**Comment by Half-Shot** [comment]
FYI, in IRC we decided to use pills in the end to ping people. I don't currently have a use for this proposal but won't close it as I don't know if other people are trying to scratch the same itch.

**Comment by turt2live** [comment]
The author has expressed interest in having this be closed (please correct me if I'm wrong).

@mscbot fcp close

**Comment by Half-Shot** [comment]
@turt2live has informed me that I can close this without a formal review if I wish. Without further ado, closing :)

**Comment by turt2live** [comment]
For context: there's no point in us forcing people through a gauntlet if they want to abandon/close/reject their own work.

**Pull request closed without merging**
