### PR TITLE
Swaggerify /login

### PR DESCRIPTION
**Pull request by illicitonion**

### CODE REVIEW

**Comment by Kegsay** [comment]
We have two endpoints: `/register` and `/login`. This PR indicates it is for `/login` but there are template variables for `{{registration_http_api}}` and the name of the YAML file is `registration.yaml` - which is it?

**Comment by illicitonion** [comment]
As far as I can tell, throughout Matrix "login" is viewed to be a subset of "registration".

I was thus assuming this file would at some point have everything registration and login related, but that I had only done the one I was about to edit.

I don't feel particularly strongly about whether they exist in one file or two, but I will admit the whole "login is a subset of registration" thing sits a little oddly with me.

**Comment by Kegsay** [comment]
I would prefer to have them separate and if we decide later to merge them, we can. I appreciate the confusion and overlap here though.

**Comment by illicitonion** [comment]
Done

**Comment by Kegsay** [comment]
LGTM

**Pull request merged**
