### PR TITLE
OpenAPI: Add missing `required` flag in `getRoomKeys`

### PR DESCRIPTION
**Pull request by ankur12-1610**
Added missing required flag in `getRoomKeys` in `matrix-doc/data/api/client-server/key_backup.yaml`.

Fixes: #3485

Signed-off-by: ankur12-1610 <anknerd.12@gmail.com>

Preview: https://pr3509--matrix-org-previews.netlify.app

### CODE REVIEW

**Comment by ankur12-1610** [comment]
@Dominaezzz can you review the changes?

**Comment by Dominaezzz** [comment]
https://pr3509--matrix-org-previews.netlify.app/client-server-api/#get_matrixclientv3room_keyskeys
Doesn't look like it's been reflected in the spec?

**Comment by ankur12-1610** [comment]
> https://pr3509--matrix-org-previews.netlify.app/client-server-api/#get_matrixclientv3room_keyskeys Doesn't look like it's been reflected in the spec?

I'll look into it :sweat_smile: 
Did I place it in wrong place? :')

**Comment by Dominaezzz** [comment]
Was on my phone so I couldn't check easily.

It's almost in the right place, it's just indented too far. Removing 4 spaces should do the trick I think.

**Comment by ankur12-1610** [comment]
> Was on my phone so I couldn't check easily.
> 
> It's almost in the right place, it's just indented too far. Removing 4 spaces should do the trick I think.

@Dominaezzz, Done :)

**Review by Dominaezzz — APPROVED** [review]
Looks like it worked! :smile:

**Pull request merged**
