### PR TITLE
/join accepts a signature for a third party invite

### PR DESCRIPTION
**Pull request by illicitonion**

### CODE REVIEW

**Comment by erikjohnston** [comment]
My only question is if it would be more appropriate for the key to be in a JSON body rather than a query param? It might make it nicer if we want to include a key id or algorithm, etc.

**Comment by illicitonion** [comment]
Done, also some tweaks and changes to reflect implementation.

**Comment by erikjohnston** [comment]
LGTM, might be worth quickly running it past @NegativeMjark

**Comment by NegativeMjark** [comment]
LGTM

**Pull request merged**
