### PR TITLE
[WIP] MSC3068: Compliance tiers

### PR DESCRIPTION
**Pull request by erkinalp**
This MSC defines several tiers of complying to Matrix specification.
[Rendered](https://github.com/matrix-org/matrix-doc/blob/a2dce5983f43c633fe9438b7b442bc1d1acea64b/proposals/3068-compliance-tiers-informational.md)

### CODE REVIEW

**Comment by turt2live** [comment]
@erkinalp I've reclassified this as a work in progress. There's several pieces missing from this proposal, such as a justification and rationale for the change. A change as critical as this should have a lot of rationale to back it up.

**Comment by erkinalp** [comment]
> such as a justification and rationale for the change

So, you consider this change as normative?

**Comment by turt2live** [comment]
It's hard to classify this MSC as anything until it's been written out more completely, other than being a work in progress. At the moment I can't judge the MSC on its merits given it does not present a justifiable case for its own consideration.

**Comment by richvdh** [comment]
I'm unclear what area of the spec this is seeking to change.

I'm also unclear what purpose the change would serve.

This PR smells of timewasting.

**Comment by erkinalp** [comment]
> I'm unclear what area of the spec this is seeking to change.
> what purpose the change would serve.

This MSC seeks to define a standard terminology for how compliant a client or a server is.

**Comment by turt2live** [comment]
There's still no justification for why we need this.

**Comment by erkinalp** [comment]
> still no justification for why we need this

Added it.

**Comment by turt2live** [comment]
I'm not convinced that this MSC is founded upon the best intentions to improve Matrix and instead appears as time wasting.

@mscbot fcp close

**Pull request closed without merging**
