### PR TITLE
Make the display name rule an override rule

### PR DESCRIPTION
**Pull request by dbkr**

### CODE REVIEW

**Comment by dbkr** [comment]
Hold on, this will affect more things than I thought.

**Comment by dbkr** [comment]
OK, this is fine: all current clients work whatever the priority class of this rule is. See https://github.com/matrix-org/synapse/pull/1011 for the synapse changes.

**Comment by richvdh** [comment]
needs changelog entry, probably with text explaining why we think we can make breaking changes.

**Comment by dbkr** [comment]
done

**Comment by richvdh** [comment]
rst is broken: http://matrix.org/speculator/spec/373/client_server/unstable.html#changelog

**Comment by richvdh** [comment]
(lgtm otherwise)

**Pull request merged**
