### PR TITLE
MSC2604: Accept device information for the login fallback endpoint

### PR DESCRIPTION
**Pull request by clokep**
[Rendered](https://github.com/matrix-org/matrix-doc/blob/clokep/login-fallback-device-info/proposals/2604-login-fallback-device-info.md)

### CODE REVIEW

**Comment by clokep** [comment]
matrix-org/synapse#5755 is an implementation for this.

**Comment by richvdh** [comment]
likewise. we'd like to get this into synapse soon so I'm going to suggest FCP

**Comment by richvdh** [comment]
@mscbot fcp merge

**Comment by turt2live** [comment]
Merged 🎉

**Pull request merged**
