### PR TITLE
Include the full schema for an http API in the docs 

### PR DESCRIPTION
**Pull request by NegativeMjark**
By resolving references to other schema files

TODO:
 * [x] Cleanup all the places that are missing titles.

### CODE REVIEW

**Comment by Kegsay** [comment]
LGTM code-wise though really needs the `NO_TITLE` things fixed before it can be merged in.

**Comment by Kegsay** [comment]
Looking at http://matrix.org/speculator/spec/141#get-matrix-client-api-v1-pushrules I see a few problems:
 - `PushRule` is included multiple times, should just be one time.
 - One of the types is `[[u'object', u'string']]` which is confusing. It looks like we're already wrapping arrays in `[ ]` so it does it twice, and we need to strip the python `u` from the string. I believe the correct type is "object or string", which may be nicer to display (e.g. `" or ".join(types)`)

**Comment by NegativeMjark** [comment]
> * PushRule is included multiple times, should just be one time.

Fixed e49ea90

> * One of the types is [[u'object', u'string']]

Fixed 8070489

**Comment by Kegsay** [comment]
LGTM - we'll need to do more PRs for descriptions/etc.

**Pull request merged**
