### PR TITLE
MSC2076: Enforce key-validity periods when validating event signatures

### PR DESCRIPTION
**Pull request by richvdh**
Rendered: https://github.com/matrix-org/matrix-doc/blob/rav/proposal/enforce_key_validity_periods/proposals/2076-enforce-validity-periods.md

### CODE REVIEW

**Comment by richvdh** [comment]
In the hope that this is relatively uncontentious:

@mscbot fcp merge

**Comment by richvdh** [comment]
related: https://github.com/matrix-org/synapse/issues/4364

**Comment by turt2live** [comment]
Spec PR: https://github.com/matrix-org/matrix-doc/pull/2080 (for when this clears FCP)

**Comment by turt2live** [comment]
merged 🎉

**Pull request merged**
