### PR TITLE
Room v2 proposal

### PR DESCRIPTION
**Pull request by erikjohnston**
This MSC proposes adding a new room version to allow servers and users to opt into using the new state resolution algorithm. Given that this does ***not*** propose making the new room version the default, nor prompting users to upgrade existing rooms, I'm hoping that this should be relatively uncontroversial.

We do not propose to make this a new default as there are several other incompatible changes to rooms we wish to make, and so its probably best to wait for those to land before changing the default and prompting people to upgrade existing rooms.

This assumes that MSC #1693 lands.

[Rendered](https://github.com/matrix-org/matrix-doc/blob/erikj/rooms_v2/proposals/1759-rooms-v2.md)

### CODE REVIEW

**Comment by erikjohnston** [comment]
Given I hope this is uncontroversial, I'm going to straight up propose an FCP

@mscbot propose merge

**Comment by turt2live** [comment]
@mscbot fcp merge

**Comment by turt2live** [comment]
3rd time's the charm?

@mscbot fcp merge

**Comment by richvdh** [comment]
A note largely for my own reference: this will use the room versioning APIs specified in https://github.com/matrix-org/matrix-doc/pull/1516.

**Comment by erikjohnston** [comment]
@mscbot reviewed

**Comment by richvdh** [comment]
implemented in https://github.com/matrix-org/synapse/pull/4307

**Comment by turt2live** [comment]
Merged via https://github.com/matrix-org/matrix-doc/pull/1773 🎉

**Pull request merged**
