### PR TITLE
Add proposal for invite error code for unsupported room version

### PR DESCRIPTION
**Pull request by erikjohnston**

### CODE REVIEW

**Comment by erikjohnston** [comment]
I think this is fairly uncontroversial, so may as well FCP it.

@mscbot fcp merge

**Comment by turt2live** [comment]
Implication of doing this is also that `/createRoom` can return the error code due to invites. I think this is fine as an extension, however.

**Comment by turt2live** [comment]
also this had disposition merge...

**Comment by turt2live** [comment]
Merged via https://github.com/matrix-org/matrix-doc/pull/1908 🎉

**Pull request merged**
