### PR TITLE
Add draft search API docs

### PR DESCRIPTION
**Pull request by erikjohnston**
This is a straw man for the search API. Hopefully it should include most of the use cases and features that people/servers may want to support.

*Note*: A lot of the API is optional, and the likelihood is that Synapse will only implement a subset of the features. The reason for including features in this design document is so that we have an idea of how those features would fit into the search API in the future.

*Note*: There are a bunch of open questions at the bottom.

[Rendered](https://github.com/matrix-org/matrix-doc/blob/erikj/search/drafts/search_api.md)

### CODE REVIEW

**Comment by ara4n** [comment]
Can you give some use cases for facets, and spell out how pagination interacts with groups/facets?

I like the idea of a slightly more structured search API than google's ?q=term, but worried this is getting too complicated and faffy for clients to implement - both for constructing the query and navigating the response.

(also, why markdown? :/)

**Comment by erikjohnston** [comment]
> Can you give some use cases for facets, and spell out how pagination interacts with groups/facets?

I'll add some examples at the bottom too.

> I like the idea of a slightly more structured search API than google's ?q=term, but worried this is getting too complicated and faffy for clients to implement - both for constructing the query and navigating the response.

Yeah, I'm a bit concerned with making sure that request/responses aren't too complicated. I think this API allows clients to ignore most of the bits if they don't need to support it.

> (also, why markdown? :/)

I completely forgot we used rst for docs :(

**Comment by Kegsay** [comment]
I like the general design. I think a few "helper" endpoints could make the API easier to use.

In the design doc, we clearly have an idea of which search type to use for which search category:
> * `m.room.message`:
>    * `content.body` - FTS
>    * `msgtype` - exact match
> * `m.room.name`:
>    * `content.name` - FTS / substring

Yet the API gives you the flexibility to choose which one:

```
POST /search
{
    "search_categories": {
        "room_events": {
            "constraints": [
                {
                    "type": "FTS",
                    "key": "content.body"
                    "value": "lazy dog",
                }
            ],
        },
    }
}
```

I propose the addition of *another* endpoint which effectively snips everything in that JSON object down to the `value`:

```
POST /search/rooms
{
  "value": "lazy dog"
}
```

Likewise, I would propose having helper endpoints for "the common use cases":

```
POST /search/profiles
{
  "value": "mike"
}
```

```
POST /search/rooms/$ROOM_ID
{
  "value": "banana"
}
```

```
POST /search/all
{
  "value": "github"
}
```

Whether this remains a JSON object for extensibility and whether we should default to arrays and not strings are open questions, but I feel some helper endpoints with "sensible defaults" would be a good improvement.

I do not propose changing the response format (though I would also propose not bothering with `groups` or `facets` for the initial cut, which keeps the response format pretty trivial).

**Comment by ara4n** [comment]
+1 to kegan's feedback

**Comment by richvdh** [comment]
can we kill this, now that a search API has landed?

**Comment by Kegsay** [comment]
@erikjohnston - what's the deal on the search API?

**Comment by erikjohnston** [comment]
The search API has landed in the main spec

**Comment by Kegsay** [comment]
@erikjohnston so this PR can be closed?

**Pull request closed without merging**
