### PR TITLE
MSC2184: Allow the use of the HTML <details> tag

### LINKED ISSUE #2182: Consider allowing the HTML <details> tag in messages
As noted in #twim:matrix.org, bot output can easily become quite large, to the point where a simple user response fills an entire screen and breaks conversation.

To offer a way to avoid this, without losing legibility or having to remove important information from bot responses, perhaps supporting the HTML `<details>` tag could be a solution. Tag references; [`<details>`](https://www.w3schools.com/tags/tag_details.asp), and [`<summary>`](https://www.w3schools.com/tags/tag_summary.asp).  
The contents of the details - and the associated summary - block would of course be subject to the normal Matrix tag rules.

I can see many places where the ability to offer both a summary and a detail view in the same message could be of huge help to bots. From RSS feed or commit updates - where a message could contain the title and link as a summary, with an excerpt as the details - to monitoring alerts where the summary could be the alert itself, and the details would contain relevant graphs or full check outputs.

### PR DESCRIPTION
**Pull request by ananace**
[Rendered](https://github.com/ananace/matrix-doc/blob/html_details/proposals/2184-allow-html-details.md)

Fixes #2182

### CODE REVIEW

**Comment by ananace** [comment]
I was a bit bored, so I did a quick mockup of the functionality by modifying the rendered Riot-web HTML for a message, just to see how it could look without anything more than a change in the allowed tag list.

MCS2182

**Comment by turt2live** [comment]
I'm getting myself into the habit of queuing things into the FCP queue:

@mscbot fcp merge

**Comment by ara4n** [comment]
I am torn - on one hand, i really like the idea. on the other hand, i can see it being quite painful for those (e.g. Riot/iOS and Riot/Android and Seaglass) who are wrapping their own HTML renderer currently.  And as @ananace quite rightly notes in the MSC, it does collide with #1767, which in theory could provide equivalent behaviour without depending on HTML to do it, and be more flexible in terms of allowing all sorts of different content/fallbacks to be togglable on & off.

What do others think?

**Comment by turt2live** [comment]
my perspective is that MSC1767 is a great thing we should definitely do, however in the interest of progress we should shove this one through. The spec does not have a requirement on any of the HTML rendering, it just leaves it as a strong recommendation. This does technically mean that implementations could just add support if they wanted to without the spec, however this seems trivial enough to just merge into the spec's recommendation.

**Comment by ananace** [comment]
I also realized that I forgot to mention that one difference between this MSC and MSC1767 is that `<details>` would support recursive usage - as well as just using it multiple times in a single message.

**Comment by anoadragon453** [comment]
I agree with @turt2live in that I don't want to block this on extensible events like so many other things.

We shouldn't block clients from using this just because some have chosen technologies which make ti difficult to implement.

**Comment by KitsuneRal** [comment]
I, too, am torn on this. I fully see the value of that tag but, aside from overlapping (I wouldn't say "colliding") with extensible events, this tag only appeared in HTML5 (I know, I know...) and, [as far as I can see](https://www.w3schools.com/TAGS/tag_details.asp), is not supported by IE. Most shamefully, HTML5 is not represented in the "Supported HTML subset" for rich text in Qt5 either, which means that - on top of poor things @ara4n mentioned - Nheko, Spectral, and Quaternion will have to go through unusual pains to render `<details>`.

With that said, the fallback is pretty clear: stripping the `<details>` tag and the `<summary>` contents entirely allows to still properly render the message. It's probably worth it to add this consideration to MSC.

One alternative to consider is to allow an attribute in `m.room.message` events that advises clients to render those events initially "collapsed" with a given content shown instead. This would emulate `<details>` functionality even if HTML is not used at all.

**Comment by erikjohnston** [comment]
> I, too, am torn on this. I fully see the value of that tag but, aside from overlapping (I wouldn't say "colliding") with extensible events, this tag only appeared in HTML5 (I know, I know...) and, [as far as I can see](https://www.w3schools.com/TAGS/tag_details.asp), is not supported by IE. Most shamefully, HTML5 is not represented in the "Supported HTML subset" for rich text in Qt5 either, which means that - on top of poor things @ara4n mentioned - Nheko, Spectral, and Quaternion will have to go through unusual pains to render `<details>`.

OOI, is there a way of implementing similar behaviour that is easier in Qt5? If not then I'd be tempted to allow this and hop/assume that future Qt version start supporting `<details>` and that they can fallback fine in the mean time.

**Comment by KitsuneRal** [comment]
> OOI, is there a way of implementing similar behaviour that is easier in Qt5? If not then I'd be tempted to allow this and hop/assume that future Qt version start supporting `<details>` and that they can fallback fine in the mean time.

Not really. The best way to emulate this in Qt would probably be parse HTML (ew), find the `<details>` block and separate it into its own widget/QML-component that expands on clicking. Alternatively, it _might_ be possible to replace `<details>` with a generic `<div>` and attach some CSS+JS to it that would expand it.

Regarding "if not" - well, the trouble is that the basic HTML subset used by Qt for simple markup inside its widgets (as opposed to full-blown web-pages that can be displayed using Qt Web Engine, which is a wrapper around Chromium) is considered a thing in itself that "happens" to be a subset of HTML4. How much they would even want to update this basic HTML engine is beyond my knowledge. In a lucky case, [Qt 6](https://www.qt.io/blog/2019/08/07/technical-vision-qt-6) will have it, almost surely not in 6.0 though. As it stands, I'm preparing to resort to one of the methods from the previous paragraph; however, since a similar trouble occurs across a few platforms, I wonder how much it's worth it.

**Comment by Alch-Emi** [comment]
I just wanted to chip in that I work in a few communities that make heavy use of content warnings, and a feature like this would be **perfect** for that usecase.  The current alternative would be using spoilers and just add text like (CW: some content warning) before, which isn't a super intuitive way of doing it.

A feature like this that makes it intuitive to add content warnings would be super helpful, and greatly appreciated (especially if clients starting selling it as content warnings, which I think could have a great effect for normalizing cws across the ecosystem, like on masto, but that might be too much to ask for :p )

**Comment by cloudrac3r** [comment]
Can we PLEASE get this to FCP? I don't believe there are any concerns outstanding.

**Comment by turt2live** [comment]
merged 🎉

**Pull request merged**
