### PR TITLE
Specify token used in /login is not an Access Token

### PR DESCRIPTION
**Pull request by anoadragon453**
While working through the implementation of /login in Dendrite, it was confusing what the contents of the token attribute in the login request body referred to.

Initially, I thought it was an access token, which made even less sense. After discovering that `token` refers to a login token instead, things became much clearer. This commit explicitly states that the token is a login token, which is separate from an access token, hopefully reducing confusion for future readers.

### CODE REVIEW

**Comment by turt2live** [comment]
Technically a server could implement it to be an access token. It's more an implementation specific token which can have some sort of meaning. In synapse, this happens to be a way to bypass registration being disabled.

**Comment by richvdh** [comment]
>  In synapse, this happens to be a way to bypass registration being disabled.

I don't think so (are you thinking of org.matrix.login.shared_secret?). It's more that it is used as a step in some login flows (eg CAS).

> Not an access token.

I do agree with Travis in that this is a bit strong (and just raises the question: "well what is it then?").

We currently have this paragraph in the "token-based login" section:

> There are many ways a client may receive a token, including via an email or from an existing logged in device.

I don't know what it is talking about with an existing logged in device, but I think it's wrong. Why not reword this paragraph to drop that reference and make it clear that login tokens and access tokens are different things?

**Comment by turt2live** [comment]
> are you thinking of org.matrix.login.shared_secret?

It appears so. Somewhere along the lines I got mixed up.

**Comment by anoadragon453** [comment]
I've reworded as I understand it, though it may be useful to add a bit explaining exactly how one would correlate a random token sent in an email with this authentication step.

**Pull request merged**
