### PR TITLE
Make the schema files JSON

### PR DESCRIPTION
**Pull request by richvdh**
This undoes a change made in PR #217.

Although JSON is a disasterous syntax for human-maintained files, the fact
remains that JSON-schema is a thing, whilst YAML-schema (although accepted by
swagger) is not. Using YAML negates most of the advantages of using the
JSON-schema format (mostly, the fact that we can feed those files into a number
of tools), and we weren't really using the increased power of YAML.

Possibly, we should consider generating the JSON from YAML inputs, but either
way, the event schemas need to refer to the JSON files, and for now it's easier
just to stick to JSON.

### CODE REVIEW

**Comment by ara4n** [comment]
So, the reason the schemas went from JSON to YAML in the first place seems to be https://github.com/matrix-org/matrix-doc/pull/207#issuecomment-162519983 - which implies that @kegsay was enthusiastic about converting everything to YAML assuming the tools were all converted to handle YAML too.  In practice this almost seems to have happened... except the README was never updated, and still tells you to use z-schema, which only accepts JSON, which seems to be the initial impetus for reverting everything to JSON.  Meanwhile, vdh's concern that JSON Schema is much more mature and established than YAML Schema seems valid (especially as we have no comments in your YAML schemas).

I've suggested that we park this until Kegan's back to discuss further, and in the interim update the README to tell you to use the right validation tool (check_examples.py or whatever it's called).

**Comment by aviraldg** [comment]
I did a fair amount of research when I filed that issue and it appears that there are *no*, or very few schema validation tools that use YAML.

**Comment by richvdh** [comment]
@Kegsay: when you have a chance, your opinion on this would be appreciated. TL;DR is that YAML means that any tooling around JSON schema (eg, validation tools) basically doesn't work when the schemas are YAMLed.

**Comment by Kegsay** [comment]
I'm opposed to going back to the days of maintaining hand-crafted JSON. From what I have interpreted, the complaint is that "We have Matrix events which are JSON, and like to use JSON Schema to generate docs for them. The tools which allow us to use JSON Schema expect the inputs are JSON, not YAML, so waaaa." - I would rather we had a pre-processing YAML to JSON script than have to suffer through touching raw JSON. Thoughts?

**Comment by richvdh** [comment]
The complaint is that there are a whole raft of tools which work with JSON Schema, and all of them expect the JSON Schema to be in JSON.

>  I would rather we had a pre-processing YAML to JSON script than have to suffer through touching raw JSON.

So would I, but we don't - hence the proposal to go back to JSON until we do - *particularly* given that the four files in question here don't really use any YAML features.

I don't feel strongly about it though.

**Comment by Kegsay** [comment]
> So would I, but we don't - hence the proposal to go back to JSON until we do

Isn't this an absolutely trivial python script to write though? I would rather time was spent making said script than backing out to JSON. Speaking as the sole maintainer (and perpetrator) of the original JSON incarnation of these schema files, it's an incredible world of pain to maintain JSON files manually, so I strongly want to avoid going back.

It seems we have agreement though that we both want to be in a world where said script exists, which is good.

**Comment by richvdh** [comment]
> Isn't this an absolutely trivial python script to write though?

I wouldn't say it's *absolutely* trivial, because of the references between files.

**Comment by richvdh** [comment]
(and yes, maintaining JSON is a pita, as `package.json` has comprehensively proven to the world)

**Comment by Kegsay** [comment]
> I wouldn't say it's absolutely trivial, because of the references between files.

Given the script is intended as an adapter for tools which can't handle YAML, I would be tempted to just walk the entire API directory and blindly convert every `*.yaml` into JSON, dumping the result into a perfect mirror API-json directory which can then be `rm -rf`d afterwards. That way you don't need to introspect the YAML at all. Sure it's a bit ming that `.yaml` files in that mirror directory will contain JSON, but it's only a temp dir for servicing the tooling, so I'm okay with that.

**Comment by richvdh** [comment]
After further discussion IRL, we agreed that the benefits of this change were outweighed by the pain of having to maintain JSON.

**Pull request closed without merging**
