### PR TITLE
Initial formal proposal for the AS API

### PR DESCRIPTION
**Pull request by ara4n**
I thought more about the requirements for application services over Christmas, and here's a slightly high-level but fairly concrete proposal of what I think they should look like.  This largely ignores policy servers and the Storage API idea, in favour of building on our current client-side gateway bots by giving them privileges and making them run as proper server-side services.

This hopefully decouples the AS API problem entirely from the CS v2 API discussion.

https://github.com/matrix-org/matrix-doc/blob/application-services/drafts/application_services.rst

### CODE REVIEW

**Comment by erikjohnston** [comment]
This looks mostly good to me.

I would be interested in the reliability mechanisms of the HTTP push transport, as the I think those will have a bearing on whether we want to support clustering of AS servers or not.

Do we want to expose the HTTP push transport for use by clients?

**Comment by ara4n** [comment]
Erik: the HTTP push transport would be usable by clients if the HS implemented it (as AS API extensions are not compulsory for an HS).  But it'd make little sense to do so.

**Comment by ara4n** [comment]
I've updated the draft with all the feedback above.  The structure of the doc is a bit weird, and the use cases haven't been fully fleshed out due to lack of time, but all the info should be there.

**Comment by Kegsay** [comment]
> is the only option if the implementer wants to avoid duplicating conversation history between the external data source and the HS.

Can we not provide a trade-off and just allow them to implement the event content? The HS would ask for the content which it would then sign/continue as normal.

> Namespaces are defined as a list of regexps against which to match room aliases, room IDs, and user IDs.

Use case for regexpping room IDs? They are opaque strings. By all means we may be selecting some existing room IDs to bridge with, but that is a far cry from the regex for room aliases, user IDs, etc. This should be made clearer.

**Comment by ara4n** [comment]
On 14/01/2015 15:17, Kegsay wrote:
>     is the only option if the implementer wants to avoid duplicating
>     conversation history between the external data source and the HS.
>
> Can we not provide a trade-off and just allow them to implement the
> event content? The HS would ask for the content which it would then
> sign/continue as normal.

Where would the HS store the signatures and all the matrix-specific 
metadata?  It feels very unwieldy for the HS to store that in its own 
DB, but separately from the actual underlying conversation data.  Hence 
suggesting that in that scenario you push the responsibility of storing 
all Matrix's data to your existing conversation store.

>     Namespaces are defined as a list of regexps against which to match
>     room aliases, room IDs, and user IDs.
>
> Use case for regexpping room IDs?

Both !.*:matrix\.org (for a vhost), and to support aliases as well as IDs.

**Comment by Kegsay** [comment]
The room ID domains are purely for namespacing the opaque ID; we shouldn't be regexpping that at all.

> Where would the HS store the signatures and all the matrix-specific metadata?

This just seems like an HS implementation problem. If the HS caches signatures (and given events are immutatatatable, why wouldn't it?) then this problem disappears. 

> It feels very unwieldy for the HS to store that in its own DB, but separately from the actual underlying conversation data. 

I don't think that is as unwieldly as you are making it out to be. Swap a json blob in a database with a URL to poke for the json blob?

**Comment by Kegsay** [comment]
> The namespace of virtual user accounts should conform to a structure like @.irc.freenode.Arathorn:matrix.org. This lets Matrix users communicate with foreign users who are not yet mapped into Matrix via 3PID mappings or through an existing non-virtual Matrix user by trying to talk to them via a gateway.

I don't think we should do this. If the user doesn't exist on Matrix then we should be 404ing/failing, not silently passing it through in the hopes that One Day they will become mapped. This also fails to account for application service namespacing (e.g. you have two very popular IRC ASes, with two different namespaces for users, which do you attempt to talk to?).

See my HTTP proposal for info on this.

**Comment by ara4n** [comment]
As per real-life discussion, I strongly think that 3rd party users should be mapped to a unique user-id in Matrix - i.e. Arathorn on irc.freenode.net should always be referred to as @/irc/irc.freenode.net/Arathorn:matrix.org or whatever the convention is.  This decouples the virtual user's identity from the AS which is performing the bridging.  And you should expect problems if you try to run two ASes against the HS bridging the same chunk of 3rd party namespace into Matrix.

Meanwhile, the actual suggested behaviour is that if I'm on Matrix and want to talk to a 3PID like Arathorn-on-irc.freenode.net, i start off by checking for a 3PID mapping in my identity server.  If the ID server has a mapping from Arathorn-on-irc.freenode.net to @arathorn:matrix.org, then we go and use that to talk to them.  Otherwise, we can choose to go via a bridge (typically our local HS's AS, but the client could be configured to use another one like matrix.freenode.net, resulting in a virtual user ID of @/irc/irc.freenode.net/Arathorn:matrix.freenode.net) - and we'll end up talking to them via the gateway.

**Comment by Kegsay** [comment]
> As per real-life discussion, I strongly think that 3rd party users should be mapped to a unique user-id in Matrix - i.e. Arathorn on irc.freenode.net should always be referred to as @/irc/irc.freenode.net/Arathorn:matrix.org or whatever the convention is.

Adding a bit more justification for this:
- The goal is to allow the client to attempt to communicate with anyone on any service outside Matrix.
- The AS provides the routing to the Outside World and is specific to a HS.

If you namespace ASes user IDs:
- The client would need to query the HS for a list of ASes running which can communicate X protocol. Multiple ASes may be returned.
- Which AS does the client choose for starters?
- The client will need to map the user's intention (I want to speak to someone on IRC freenode) to some string they get back from the HS (which may even look like ``.irc.freenode.``)
- The client then needs to craft the user ID and send a message.

If you don't namespace ASes user IDs:
- The client can work out the user ID by convention, without needing to hit the HS (e.g. They are URIs, replace ``/`` with ``.`` or something)
- Only 1 AS *should* ever be running for a particular namespace of user IDs, and it's the HS server admin's fault if there are conflicts around this. (Note that this isn't always a negative thing, e.g. one AS may provide logging facilities for IRC rather than routing, and so will not conflict with the other AS doing the routing)

We may still want to consider a layer of indirection (e.g. "here is a  random URI, please give user ID") rather than regexpping the URI to form an ugly looking user ID, or we may want slightly nicer conversion rules (this will depend on https://github.com/matrix-org/matrix-doc/pull/3 )

**Comment by Kegsay** [comment]
> If the HS receives an invite to an unknown room which is in the namespace delegated to the AS, then the HS queries the AS for the existence of that room

When would this ever happen? If the non-matrix user sends a message, the AS will make a room and invite the matrix user to it. If the matrix user sends a message,
the room must already exist. Can you give an example when this would be required / expected behaviour?

Also, can you justify why the lazy-loading of user IDs is absolutely required? (e.g. so you don't need to create every MSISDN evar). It's briefly touched on but not explained why it is important.

**Comment by ara4n** [comment]
This is describing the HS receiving an invite (or join) from matrix for a virtual room which needs to be lazy-created by the AS.

So: if your HS is hooked up to an IRC bridge AS which has registered control of the #/irc/irc.freenode.net/ namespace, then if the HS receives an invite/join from a Matrix user on that HS to participate in #/irc/irc.freenode.net/randomchannel, it's possible the HS knows nothing about this room yet, as it's never been accessed before.  In this scenario, the HS sees that namespace is delegated to the AS, so queries the AS as to whether that room should exist and be lazy-created.  The AS checks if that channel exists on the IRC server, and if so, the AS then goes and creates the room on the HS via the AS/CS API - creating the room with the right alias, name, permissions, history, state, etc and inserting the appropriate virtual users to represent the ones in the IRC channel.  Once this is done, the HS continues on with the normal interaction with the new lazy-created room.

The reason why we need lazy-loading of user IDs is because another AS might be PSTN-gatewaying the entire MSISDN space - e.g. supporting @.tel.447700900123:whoever.com style user IDs.  The space of possible valid MSISDNs is obviously huge: 10^13 or so.  So when you start a conversation with one of these virtual users, they must be lazily provisioned by the AS.  (For instance, the AS could reject the invite if it can't route to the given MSISDN.  Alternatively, it provisions an account on the HS for that user's name, with appropriate profile info based on what it knows about that MSISDN and metadata about how it's bridging it).  It's insane to think that the AS would preprovision accounts for all possible MSISDNs on the HS that it could gateway through to.

**Comment by NegativeMjark** [comment]
Would it be helpful for the HS to include display name info for users and rooms when pushing events to the AS? It would save the AS from having to track what the current display name is for a user.

**Comment by ara4n** [comment]
We have an open problem in general on how to specify 3PID originators in 
Matrix.

If I've logged into my Matrix app with my MSISDN, and send a message to 
a hypothetical Matrix->Email gateway as 
@.mailto.someone@matrix.org:mailgateway.com (or whatever the URI is): 
what should the From and Reply-To header in the email be?  Should it be: 
"Display Name" <arbitrary-uid@mailgateway.com>?  Or should it be 
<matthew:matrix.org@mailgateway.com>? Or should it be 
<MSISDN@mailgateway.com>?

In general we don't want to leak Matrix IDs if users are identifying 
themselves (i.e. logged in as) with a 3PID.  Therefore we need a way to 
pass both originator 3PID and Display Names through to the foreign 
network (assuming the foreign network supports the concepts of display 
names or displaying 3PIDs).

**Comment by ara4n** [comment]
Also, these virtual user IDs are getting uglier and uglier.  Is there 
any way we can mux the actual remote URI into the name of the virtual 
user?  E.g. allocate virtual user IDs as a SHA-1 style hash of the URI?

so: the virtual user id for the foreign matthew@arasphere.net user on a 
hypothetical Matrix<->Email AS gateway would be 
@{SHA-1('mailto:matthew@arasphere.net'}:emailgateway.com - or 
@bec6ec1b384538d78873214cf8cdff4cc4415288:emailgateway.com?  (The 
displayname and email-address profile field of this virtual user would 
be set to "matthew@arasphere.net", and/or the displayname could be set 
to the GECOS learned from any inbound mails from this foreign user.)

**Comment by Kegsay** [comment]
> allocate virtual user IDs as a SHA-1 style hash of the URI?

I like this, but what namespace does the AS claim then? An alternative would be to do as I suggested a few comments up: 

> We may still want to consider a layer of indirection (e.g. "here is a random URI, please give user ID") rather than regexpping the URI to form an ugly looking user ID

though I prefer your hash idea since it avoids adding another API and another round trip.

**Comment by Kegsay** [comment]
Some application services may want exclusive rights on the namespaces they've claimed in the regex, e.g. to stop humans creating a room alias / user in the AS namespace. Other application services may not want exclusive rights but just want to sniff around (e.g. logging ASes). 

This concept isn't covered in the general API.

**Comment by Kegsay** [comment]
Sometimes application services need to create rooms (e.g. when lazy loading from room aliases). Created rooms need to have a user that created them, so federation works (as it relies on an entry existing in ``m.room.member``). We should be able to add metadata to ``m.room.member`` to state that this user is an application service, a virtual user, etc.

**Pull request merged**
