### PR TITLE
CS API YAML janitoring

### PR DESCRIPTION
**Pull request by KitsuneRal**
A pack of commits simplifying and cleaning up the spec code.

### CODE REVIEW

**Comment by turt2live** [comment]
> One doesn't need to put another level of nesting to object schemas just because a structure has allOf along with other properties.

I'm starting to think this is a problem of preference and not so much of validity of the swagger. Personally, I prefer the form the spec currently has because it is more clear about the nesting structure (which is why I use it everywhere). It'd be great if we can, as a team, come up with a decision and put it in the code style document instead of having these subtle back and forths all the time about it :/

**Comment by richvdh** [comment]
> It'd be great if we can, as a team, come up with a decision and put it in the code style document instead of having these subtle back and forths all the time about it :/

Agreed. Personally I don't have strong feelings either way, but I feel like I recently reviewed a PR which made a bunch of changes in the opposite direction (though I can't immediately find it). Let's certainly not get into the business of flipping back and forth on it.

@KitsuneRal do you have strong reasons for feeling that we ought to flatten these out?

**Comment by turt2live** [comment]
This seems to have fallen into a pit of merge conflicts and bureaucracy that never happened. @KitsuneRal if you're still interested in this, please open a new PR with the merge conflicts resolved (and probably with a conversation at a retro).

**Comment by KitsuneRal** [comment]
Thanks for reminding. By now I agree that flattening is a matter of personal preference, and I have added better support of `allOf` into my code generator anyway. The two other commits are still relevant and will come in another cleanup PR.

**Pull request closed without merging**
