### PR TITLE
Render enums inside additionalProps as one more table

### PR DESCRIPTION
**Pull request by KitsuneRal**
`/capabilities` uses `additionalProperties` that maps to an enum value. The code parsing `additionalProperties` almost doesn't use the Swagger data on the enum, leading to #2242. This PR adds rendering the data on enum into another table.

### CODE REVIEW

**Comment by KitsuneRal** [comment]
I wonder if a changelog entry should be supplied with this.

**Comment by turt2live** [comment]
Yes, it should. Probably something like "Clarify the available enum values for the room versions capability".

**Comment by turt2live** [comment]
(dev scripts build failure is probably a false positive - try merging master into your branch and it should go away)

**Comment by KitsuneRal** [comment]
Seems like we're good to go now?

**Comment by turt2live** [comment]
Yup!

**Comment by jplatte** [comment]
This part of the spec has actually become worse with 0.6.1, and it does seem to be because of this change. There is no longer anything tying `RoomVersionStability` to `RoomVersionsCapability`.

**before:** room_versions_0 6 0

**after:** room_versions_0 6 1

**Comment by turt2live** [comment]
@jplatte that's probably a simple typing error on our part. Please open a new issue instead of commenting on closed/merged changes, as we typically will not notice.

**Pull request merged**
