### PR TITLE
Add identicon spec

### PR DESCRIPTION
**Pull request by turt2live**
Adds a spec for identicons, based on the synapse implementation: https://github.com/matrix-org/synapse/blob/master/synapse/rest/media/v1/identicon_resource.py

### CODE REVIEW

**Comment by ara4n** [comment]
hum. i wonder whether we really want this in the spec in the end. i kinda regret adding it in the first place, as the aesthetics for placeholder avatars end up being a very client-specific thing.  (github like identicons look ugly in riot, for instance)...

**Comment by turt2live** [comment]
It seems like something that could be useful to other clients while at the same time looking like it's leftover from matrix console. The only reason I opened this is because I was checking compatibility for the media repo I'm working on, and this endpoint was missing.

**Comment by ara4n** [comment]
I really feel that the whole thing (which was originally my idea, iirc) was a total misadventure, unfortunately - the concept of an algorithmically generated avatar which is then consistent over all of Matrix just ends up looking ugly, as clients want to render unknown users in a manner which works for them.  We haven't implemented it in dendrite and have no intention of doing so, so I'd consider this a weird quirk of old synapse history which never made it into the spec and should be consigned to the annals of history - the Matrix spec is bloated enough without adding in functionality which can be done much much better by other services or clientside libraries.

@erikjohnston, @richvdh, please yell if you disagree.

@turt2live sorry for the potentially wasted time on this :/

Is your media repo foss btw?

**Comment by turt2live** [comment]
No hard feelings :) This is something that is kinda a stretch for spec anyways.

The media repo I'm working on is available here: https://github.com/turt2live/matrix-media-repo
It's more targeted at being the media repo for multiple homeservers, deduplicating media across all of them.

**Comment by ara4n** [comment]
cool! shocked I hadn't seen matrix-media-repo before. did you look at the dendrite one at all, ooi (or have any idea how it compares)?

**Comment by turt2live** [comment]
I've looked at the dendrite one (mostly to figure out how thumbnailing works), but haven't done much performance testing. In theory it performs about the same.

**Comment by richvdh** [comment]
yup let's keep this out of the spec. Sorry Travis.

**Pull request closed without merging**
