### PR TITLE
🚀 Make OpenAPI definition available

### PR DESCRIPTION
**Pull request by afranke**
This will make it part of upcoming releases and will make it unnecessary to commit it manually to the matrix.org repository after each of them.

Preview: https://pr3542--matrix-org-previews.netlify.app

### CODE REVIEW

**Comment by afranke** [comment]
https://pr3542--matrix-org-previews.netlify.app/client-server-api/api.json is indeed a thing. :raised_hands:

**Review by turt2live — COMMENTED** [review]
thanks! Can the same treatment be applied to the historical spec build job too please?

**Comment by afranke** [comment]
Good catch, done.

**Review by turt2live — APPROVED** [review]
thanks :)

**Pull request merged**
