### PR TITLE
Specify the minimum CSP for media

### PR DESCRIPTION
**Pull request by turt2live**
Rendered: see 'docs' status check

----

Fixes https://github.com/matrix-org/matrix-doc/issues/1066

### CODE REVIEW

**Comment by erikjohnston** [comment]
I'm not sure we want to be so restrictive, all of this would be unnecessary for media hosted on other domains

**Comment by turt2live** [comment]
We can't guarantee that people respect that recommendation though. We can however try to tell servers what to do.

Fwiw, this is the csp used in synapse.

**Comment by erikjohnston** [comment]
We can't guarantee that people respect any recommendation at all, so I'm not sure I really follow your point.

There's two issues here:

1. I'm not at all convinced that that CSP is either necessary or sufficient security going forward.
2. That CSP is not at all user friendly, as it blocks a lot of stuff that end users may want to use (which is why we whitelist PDFs).

I'm not keen on mandating it given those concerns. Having a `MUST` saying that the server must protect clients against such attacks with recommendations would make me feel much happier

**Comment by turt2live** [comment]
@erikjohnston I've dialed back the language a bit. Please take a look.

**Comment by erikjohnston** [comment]
Thanks. I'd be sorely tempted to mandate the server does something to protect web clients, but its fine for now

**Pull request merged**
