### PR TITLE
Fix broken link in end_to_end_encryption.md

### PR DESCRIPTION
**Pull request by jplatte**
Preview: https://pr3708--matrix-org-previews.netlify.app

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
Thanks! If you get a chance, can we get a "Fix various typos throughout the specification." changelog entry for this please?

If not, I'll add it in when merging.

**Comment by jplatte** [comment]
How do I do that, actually? I see there's a `changelogs` directory, but it's per-spec (client_server, server_server, ..) and per-issue while it sounds like you want me to add some sort of catch-all thing where the next typo fix will be referenced as well rather than being its own changelog entry.

**Comment by uhoreg** [comment]
You can just create a file in `changelogs/client_server/newsfragments`, named after the PR number and change type (in this case, the file would be named `3708.clarification`), containing the exact text that Travis wrote in his comment.  The idea is that if we use that text for all the typo correction PRs, our changelog tool will notice that multiple PRs have the same text and will lump them all together in one entry, rather than giving each one their own entry.  (At least, that's how it used to work -- the new changelog doesn't seem to do that any more. :frowning_face: )

**Comment by richvdh** [comment]
changelog added in [4ab9286](https://github.com/jplatte/matrix-doc/commit/4ab9286a70ea9824efc3fd826b2a297885b0ae3d)

> (At least, that's how it used to work -- the new changelog doesn't seem to do that any more. frowning_face )

It should do - citation needed?

**Comment by uhoreg** [comment]
> > (At least, that's how it used to work -- the new changelog doesn't seem to do that any more. frowning_face )
> 
> It should do - citation needed?

On https://spec.matrix.org/v1.2/changelog/ for "Changes since last release", I see things like:

image

where it has one line per PR, whereas for the v1.1 changes, I see:

image

one line for 3 PRs

**Pull request merged**
