### PR TITLE
Add event as a parent for all event types

### PR DESCRIPTION
**Pull request by gergelypolonkai**
Signed-off-by: Gergely Polonkai <gergely@polonkai.eu>

### CODE REVIEW

**Comment by richvdh** [comment]
@matrixbot: test this please

**Comment by richvdh** [comment]
@gergelypolonkai: this is no doubt correct. Does it actually make any practical difference, out of interest?

**Comment by gergelypolonkai** [comment]
Other than easier maintenance later, not really. The current event schemas are just fine and usable, I just applied a bit of DRY to them.

**Comment by richvdh** [comment]
Fair enough!

**Pull request merged**
