### PR TITLE
m.login.token

### PR DESCRIPTION
**Pull request by erikjohnston**

### CODE REVIEW

**Comment by illicitonion** [comment]
LGTM

**Comment by ara4n** [comment]
Are there any restrictions on how this token should be scoped (is it meant to be one-time?)  An example use case could be helpful to understand how this is meant to be used.  Why is 'nonce' called a nonce, if it's just a UID?

**Comment by Kegsay** [comment]
I'm not sure how the `nonce` is supposed to work beyond providing idempotency here. There seemingly isn't any correlation between it and the `token` provided. How does it protect against replay attacks? The docs don't seem to mention when the token is invalidated.

**Comment by erikjohnston** [comment]
> Are there any restrictions on how this token should be scoped (is it meant to be one-time?)

Depends on the token in question. It probably will be one time in most circumstances.

> An example use case could be helpful to understand how this is meant to be used.

For example, using an existing logged in device to log in a new one. Would be useful for mobile apps to be able to scan a one time QR code to log in.

> Why is 'nonce' called a nonce, if it's just a UID?

I guess. Its function is to allow the server to do one time tokens while still allowing retries, i.e. a server will reject anyone else trying to use that token with a different `nonce`/`uid`. The main requirement is that its non-guessable by third parties.

**Comment by erikjohnston** [comment]
How about `txn_id` ?

**Comment by Kegsay** [comment]
We should probably state for how long after consuming the `nonce`/`txn_id` you can still get an `access_token` for, else that could be fun if I can reuse the same token/nonce combo in like 3 days time.

**Comment by erikjohnston** [comment]
Hmm, interesting point. What do we say for other APIs where we use `txn_id`s?

**Comment by Kegsay** [comment]
The only APIs which use `txn_ids` are for sending events in a room which then NOP on subsequent requests since the event has already been sent. AFAIK it will persist in-memory the last few `txn_ids` and doesn't expire them (it doesn't need to as there isn't potential security leakage like this has with returning an `access_token` days after the initial request)

**Comment by erikjohnston** [comment]
It would probably be enough to invalidate the `token` after we see the client using the `access_token`? In which case it is an implementation detail? (The tokens may also invalidate themselves after a short time, or they may not)

**Comment by Kegsay** [comment]
I would rather not leave this open to interpretation given the sensitive nature of the data. We should probably state that on receipt of a valid token it will be valid for up to X seconds (if this is literally just for retries at the HTTP-level, then really anything > 5 minutes would be crazy, so perhaps X=300?) Specifying an upper-bound ticks the due diligence box whilst still giving implementations some flexibility depending on how far on the paranoia scale they are.

**Comment by erikjohnston** [comment]
5 minutes is not really enough if you suddenly disappear into the underground for 20mins, and then come out only to discover that your one time token is now invalid. Depending on where you got the token, it may be easy or impossible to get another one

Also, what attacks are you trying to protect against here? The only way both the `txn_id` and `token` can be leaked is if they are MITM'ing the connection or have infiltrated the device, and even if an attacker gets both the token could only be used again between the actual device receives the token and it using it.

It's also worth noting that this spec doesn't actually specify currently that the token *must* be one use.

**Comment by Kegsay** [comment]
> even if an attacker gets both the token could only be used again between the actual device receives the token and it using it.

You don't specify anywhere about scoping these tokens to a device.

I don't really see what the point of the `txn_id` is then. Why can't we ensure idempotency via the `token` / `user_id` combo itself if it isn't a one-time use thing (because I can resend the same request on the same device and get a response back). It's not like that can be confused with another login using a token, right?

**Comment by erikjohnston** [comment]
> You don't specify anywhere about scoping these tokens to a device.

That's more up to the thing generating the tokens. This is meant to be a general purpose API that supports a lot of different token based use cases. The details of the scoping of a token would be specced us part of whatever was generating the token.

> I don't really see what the point of the txn_id is then. Why can't we ensure idempotency via the token / user_id combo itself if it isn't a one-time use thing (because I can resend the same request on the same device and get a response back). It's not like that can be confused with another login using a token, right?

The point of the `txn_id` is that once a token gets tied (on the server) to a `txn_id`, the token *can* be invalidated so that it only works with that `txn_id` if that is something the server wants to do. This is really only useful if the `txn_id` isn't guessable, so using the `user_id` isn't really an option.

More concretely, some example use cases:

- Having a logged in device display a QR code that encodes a token, which can be used as a one shot log in for a mobile device. The token would have a short lifetime as they would be easy to regenerate. 
- Getting emailed a token by a server admin after you've locked yourself out of your (corporate?) account. These would be longer lived, since its harder to get new ones.
- Having a backup token stored in a safe, which *never* expires, as a backup. May or may not be one shot.
- Using public key crypto to log in, where the token is some form of signature to verify you.

**Comment by Kegsay** [comment]
> The point of the `txn_id` is that once a token gets tied (on the server) to a `txn_id`, the token can be invalidated so that it only works with that `txn_id` if that is something the server wants to do. 

So I guess this protects against something like:
 - Expose a QR code as a token for Alice's account.
 - Alice scans the QR code.
 - Alice logs in using the token.
 - Alice leaves her computer and Bob comes along and scans the QR code.
 - Bob then tries to log in using the token but is rejected because the token is now "tied" to Alice's `txn_id`.

Is this correct? If so, it would be good to document *why* we need the `txn_id` e.g. exactly what I just quoted from you above. This still falls under the:

> general purpose API that supports a lot of different token based use cases.

so I think it would be good to include.

**Comment by erikjohnston** [comment]
> .... Is this correct? 

Yup.

> so I think it would be good to include.

So something like: 

>The `txn_id` may be used by the server to disallow other devices from using the token, thus providing "single use" tokens while still allowing the device to retry the request. This would be done by tying the `token` to the `txn_id` server side, as well as potentially invalidating the `token` completely once the device has successfully logged in (e.g. when we receive a request from the newly provisioned `access_token`)

?

**Comment by erikjohnston** [comment]
Maybe we should also be mandating that the token is a macaroon?

**Comment by Kegsay** [comment]
Mandating macaroons is at odds with your intent though if it is:

> a general purpose API that supports a lot of different token based use cases.

I don't know the implications of the decision to enforce macaroons (e.g. implications for clients having to know they exist, implications for <insert random way of getting a token> to know about macaroons).

> So something like:
>> The txn_id may be used by the server to disallow other devices from using the token, thus providing "single use" tokens while still allowing the device to retry the request. This would be done by tying the token to the txn_id server side, as well as potentially invalidating the token completely once the device has successfully logged in (e.g. when we receive a request from the newly provisioned access_token)

LGTM (and also LGTM for the PR in general after this)

**Pull request merged**
