### PR TITLE
Document guest_access in /createRoom presets; Make presets a table

### PR DESCRIPTION
**Pull request by turt2live**
Previously the presets ended up being rendered as one long string (the indentation was not respected). This was hard to read and wasn't very clear.

Now that there's a larger amount of information, it makes some sense to put it into a table. Tables don't work nicely when nested in another table, so the preset definitions have been moved into the general route description.

This commit also updates the documentation to reference `preset`, not `presets` given the param is singular.

Fixes https://github.com/matrix-org/matrix-doc/issues/881

-----

Rendered: https://pr1379.matrix-spec.t2host.io/client_server/unstable.html#post-matrix-client-r0-createroom

This PR documents existing behaviour and does not attempt to improve or change the situation.

Reference: https://github.com/matrix-org/synapse/blob/752b7b32ed1c33651c0c64fbbb4289c3b62ac89b/synapse/handlers/room.py#L43-L62

### CODE REVIEW

**Comment by turt2live** [comment]
@KitsuneRal and @mujx - would be nice to get your review on this one :)

And yes, I realize that the `Other` column doesn't extend all the way - the renderer doesn't care and it would suck to have to adjust that every time there's an edit in the column.

**Comment by mujx** [comment]
Isn't it a little counter-intuitive that in a `private` chat guests are allowed but not in the `public` preset?

**Comment by turt2live** [comment]
@mujx that would unfortunately have to go through the proposal process. This PR is on the critical path of documenting existing behaviour.

**Comment by mujx** [comment]
@turt2live Oh sorry, I missed that part on the description.

**Comment by turt2live** [comment]
No worries. Thanks for taking a look!

**Comment by turt2live** [comment]
(I've filed your suggestion for improving the presets as https://github.com/matrix-org/matrix-doc/issues/1415)

**Pull request merged**
