### PR TITLE
Add missing enum fields for the set_presence parameter

### PR DESCRIPTION
**Pull request by mujx**

### CODE REVIEW

**Comment by richvdh** [comment]
ok to test

**Comment by richvdh** [comment]
@mujx: are you sure? What makes you believe that other values are valid here?

The description only documents `offline`, so if other values are valid, they need documenting too.

**Comment by mujx** [comment]
I thought that the presence parameter would support all the values from the [presence endpoints.](https://matrix.org/speculator/spec/HEAD/client_server/unstable.html#put-matrix-client-unstable-presence-userid-status). If I'm wrong and only one value is allowed why not convert it into a boolean?

**Comment by leonerd** [comment]
I believe all the values should be allowed. At least, that was my intention when I designed it :)

**Comment by maxidor** [comment]
@richvdh Any update on this?

**Comment by richvdh** [comment]
> The description only documents offline, so if other values are valid, they need documenting too.

**Comment by turt2live** [comment]
@mujx are you able to update this to include descriptions? Given the age, it'd be nice to have this be merged :)

**Comment by turt2live** [comment]
@mujx Thank you for this PR! I hope you don't mind that I've added the requested descriptions to the PR. Stuff like this is very much part of the "end of August" goal for the spec, which happens to be in just a few short days.

It's worth noting that synapse currently does not support `unavailable` as an option, however as per leo's comment above, it seems reasonable to expect it in the spec and have the implementation follow.

I've also merged the latest master into the branch so that the PR can benefit from the new changelog format and build process.

**Comment by mujx** [comment]
Thanks @turt2live for finishing the PR. I've forgotten about the PR because I wasn't sure what `unavailable` really means in that context.

**Pull request merged**
