### PR TITLE
add information about Perspectives

### PR DESCRIPTION
**Pull request by uhoreg**
I quickly wrote something about how Perspectives works.  Someone should probably double check to make sure that what I wrote matches what Matrix really does, but at least this should be a start.

### CODE REVIEW

**Comment by richvdh** [comment]
somehow this has got mixed up with a patch which renames riot to vector. Please could you undo that?

@erikjohnston, can you comment on the veracity of the perspectives bits?

**Comment by uhoreg** [comment]
Sorry, I must have made my PR at around the same time that my other PR was applied, which must have confused GitHub.  I'll fix it up.

**Comment by uhoreg** [comment]
Fixed (my personal copy was lagging behind).

**Comment by richvdh** [comment]
thanks!

ok to test

**Comment by erikjohnston** [comment]
LGTM, might want to check with @NegativeMjark who was the person behind that

**Comment by NegativeMjark** [comment]
LGTM

**Pull request merged**
