### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by Dominaezzz**

### CODE REVIEW

**Comment by t3chguy** [comment]
Ignore my fat-fingered approval :D

**Comment by Dominaezzz** [comment]
Ha, I forgot you had power here. Doesn't look like GitHub supports sign-off in the UI :weary:. Clone time.

**Comment by Dominaezzz** [comment]
Changelog for a typo??

**Comment by turt2live** [comment]
yes, copy `2136.clarification` to a file named `2215.clarification`

**Comment by ara4n** [comment]
thanks! sorry for the sign-off (which honestly is probably ignorable for an utterly trivial change like this) and the changelog (which the CI forces us to do).

**Pull request merged**
