### PR TITLE
spec lazy_load_members and include_redundant_members

### PR DESCRIPTION
**Pull request by ara4n**
as per https://github.com/matrix-org/matrix-doc/issues/1227

### CODE REVIEW

**Comment by ara4n** [comment]
this needs to handle the question of how we negotiate the presence of LL (it might just be checking for version > 0.4.0) before being merged.  See also #1497

**Comment by KitsuneRal** [comment]
As I got to implementing this in libQMatrixClient - these two parameters only make sense (and effect) if supplied in the `state` section of the filter. Maybe move them to `sync_filter.yaml` then? I'll draft the proposed change and post the link here.

**Comment by KitsuneRal** [comment]
This should be better: https://github.com/QMatrixClient/matrix-doc/commit/fb612be454abeaaa27d2529fce77f10518263f7c

**Comment by KitsuneRal** [comment]
Independent implementation interoperable with the current Synapse develop: https://github.com/QMatrixClient/libqmatrixclient/pull/263

**Comment by KitsuneRal** [comment]
By the way, what is the (older) Synapse reaction if I supply `lazy_load_members` in a filter?

**Comment by richvdh** [comment]
> By the way, what is the (older) Synapse reaction if I supply lazy_load_members in a filter but the homeserver doesn't support it?

synapse ignores unrecognised fields in filters

**Comment by bwindels** [comment]
Not sure this is mentioned in any of the related Google docs or elsewhere, but I remember we decided towards the end of implementing LL that the server should always send the membership event during initial sync for the syncing user.

**Comment by KitsuneRal** [comment]
Should this be closed now that #1758 is in?

**Comment by turt2live** [comment]
This looks redundant - closing.

**Pull request closed without merging**
