### PR TITLE
Reorganize event structure in c2s spec and clarify event capabilities

### PR DESCRIPTION
**Pull request by turt2live**
Fixes https://github.com/matrix-org/matrix-doc/issues/1166
Fixes https://github.com/matrix-org/matrix-doc/issues/1527
Fixes https://github.com/matrix-org/matrix-doc/issues/1827

Note: In order to fix the "state events have the following fields: [no words]" bug (1827) we need to resolve references on common event types. When doing this we ultimately end up with more fields than may be required to explain the section, however this commit alters the section descriptions to just say "these fields" instead of "these additional fields".

This is also preferable over trying to get the inheritance reversed in the common event types, as the `/sync` endpoint has a high amount of reliance on partial events definitions.

### CODE REVIEW

**Comment by ara4n** [comment]
lgtm, depending on what it actually looks like with the expanded "events have these fields", "state events have these fields" style tables.  hopefully the duplication isn't too painful.

**Comment by turt2live** [comment]
It's not great, but I think it's at least clear and not confusing:
https://6829-24998719-gh.circle-artifacts.com/0/root/project/scripts/gen/client_server/unstable.html#room-event-fields

**Comment by ara4n** [comment]
yeah, it's not ideal - ~10 out of the ~12 fields are the same?

could we just cheat and hardcode it rather than generating it from the swagger, to avoid it being icky?

**Comment by turt2live** [comment]
Yea, I'll just hardcode the state events section. The room events can probably stay autogenerated because they have the most fields.

**Comment by ara4n** [comment]
needs moar `prev_content`

**Comment by turt2live** [comment]
this was lgtm'd out of band

**Pull request merged**
