### PR TITLE
Make m.notice description use stricter language

### PR DESCRIPTION
**Pull request by kyrias**

### CODE REVIEW

**Comment by dbkr** [comment]
Seems reasonable, although for consistency we probably ought to stick with single-space-after-full-stop. @richvdh wdyt?

**Comment by kyrias** [comment]
Ah, sorry, I double space out of habit.  Doesn't make a difference for the generated HTML of course, but I'll push a fixed version if the rest seems okay.

**Comment by uhoreg** [comment]
"visually distinct" doesn't make sense for speech- or Braille-based UIs.  Perhaps the suggested wording could be altered to something along the lines of "... clients should present ``m.notice`` messages to users in a distinct manner..."?

**Comment by kyrias** [comment]
Thank you @uhoreg, updated with your suggestion.

**Comment by richvdh** [comment]
matrixbot: test this please

**Comment by richvdh** [comment]
lgtm.

A comment for the changelog (https://github.com/matrix-org/matrix-doc/blob/master/changelogs/client_server.rst) would be appreciated.

**Comment by kyrias** [comment]
Added the comment

**Comment by richvdh** [comment]
tyvm!

**Pull request merged**
