### PR TITLE
Remove /notify from client-server API

### PR DESCRIPTION
**Pull request by illicitonion**

### CODE REVIEW

**Comment by Kegsay** [comment]
As per SPEC-250 - this stuff should really live in a 4th spec.

**Comment by illicitonion** [comment]
Fancy writing the place-holder page for that spec? I know nothing about push.

**Comment by Kegsay** [comment]
Done

**Comment by illicitonion** [comment]
Your additions LGTM, do my removals LGTY? :)

**Comment by illicitonion** [comment]
(Also, note that this isn't currently linked to from intro.rst)

**Comment by Kegsay** [comment]
LGTM

**Pull request merged**
