### PR TITLE
Consolidate backwards-compatible client changes

### PR DESCRIPTION
**Pull request by remram44**
You have two sections for the same things.

`Signed-off-by: Remi Rampin <remirampin@gmail.com>`

### CODE REVIEW

**Comment by turt2live** [comment]
I believe the intention behind this split is to isolate the difference between things that are brand new to the spec and things which have been modified.

**Comment by turt2live** [comment]
There's a few that were in the backwards-compatible changes that should be in the new endpoints. However, there's also a few that aren't new endpoints.

**Comment by remram44** [comment]
That doesn't seem to be the case at all. Are we looking at the same thing? The [rendered version of my change is here](https://github.com/remram44/matrix-doc/blob/patch-1/changelogs/client_server.rst).

As you can see, the new endpoints are in a subsection of the backwards compatible changes. Only new endpoints are there, and no new endpoints are out of there.

**Comment by turt2live** [comment]
Oh, I'm dumb and didn't realize it was indented differently. The diff made it look like it was just cut+paste higher.

Sorry about that.

**Comment by turt2live** [comment]
... but it was cut+paste and I see the issue now.

**Comment by turt2live** [comment]
@remram44 before I can merge this, I need your sign off: https://github.com/matrix-org/matrix-doc/blob/master/CONTRIBUTING.rst#sign-off

The TLDR is to put the following in a github comment:
```
Signed-off-by: Real Name <your.email@domain.com>
```

**Comment by remram44** [comment]
I missed that part of the guide :sweat_smile: Added to PR description.

**Comment by turt2live** [comment]
Thanks :)

**Pull request merged**
