### PR TITLE
MSC1831: Change the order of .well-known and SRV discovery techniques

### PR DESCRIPTION
**Pull request by turt2live**
[Rendered](https://github.com/matrix-org/matrix-doc/blob/travis/msc/wk-before-srv/proposals/1831-srv-after-wellknown.md)

### CODE REVIEW

**Comment by turt2live** [comment]
In the interest of getting this into the r0 s2s spec release, I'm calling for a 24 hour FCP on this. Because the bot can't handle this, I'm channelling it here.

----

Team member @turt2live has proposed to merge this. The next step is review by the rest of the tagged people:

* [ ] @KitsuneRal
* [ ] @anoadragon453
* [ ] @ara4n
* [ ] @dbkr
* [ ] @erikjohnston
* [ ] @richvdh
* [x] @turt2live
* [ ] @uhoreg

No concerns currently listed.

Once a majority of reviewers approve (and none object), this will enter its final comment period. If you spot a major issue that hasn't been raised at any point in this process, please speak up!

See [this document](https://github.com/matrix-org/mscbot/blob/anoa/matrixify/README.md) for info about what commands tagged team members can give me.

**Comment by anoadragon453** [comment]
Looks good to me.

@turt2live reviewed

**Comment by richvdh** [comment]
thanks @turt2live

**Comment by richvdh** [comment]
To be clear: this change makes it easier for servers to migrate to the new system.

In order to be compatible with requests from both Synapse 0.34 and 1.0, servers can have both a SRV and a .well-known file, with Synapse presenting a certificate corresponding to the target of the .well-known. Synapse 0.34 is then happy because it will follow the SRV (and won't care about the incorrect certificate); Synapse 1.0 is happy because it will follow the .well-known (and will see the correct cert).

**Comment by richvdh** [comment]
(With MSC1708 as originally written, it was impossible to have a server which was compatible with both 0.34 and 1.0 without it presenting the cert corresponding to the original matrix domain: If you use a SRV, 0.34 would be happy but 1.0 would complain about the broken cert. If you *don't* use a SRV, and instead use a .well-known, 1.0 would be happy but 0.34 would be unable to follow the routing. Your only option was therefore to wait until everyone had updated to 0.99, and then, *before* anyone updates to 1.0, remove the SRV and add the .well-known.)

**Comment by dbkr** [comment]
lgtm with the explanation of the problem :)

**Comment by turt2live** [comment]
because I'm the bot for this one: T minus 24 hours:

----

:bell: **This is now entering its final comment period**, as per the [review above](https://github.com/matrix-org/matrix-doc/pull/1831#issuecomment-459426431). :bell:

**Comment by turt2live** [comment]
The final comment period, with a disposition to **merge**, as per the [review above](https://github.com/matrix-org/matrix-doc/pull/1831#issuecomment-459426431), is now **complete**.

**Comment by turt2live** [comment]
Note: this skips straight to merge as the spec PR was reviewed and merged while this was in FCP. No changes have been proposed between that happening and now, and thus no further changes to the spec are required at this time for this MSC.

**Pull request merged**
