### PR TITLE
MSC2033: Adding a device_id to /account/whoami

### PR DESCRIPTION
**Pull request by turt2live**

### CODE REVIEW

**Comment by joepie91** [comment]
__Usecase:__ I'm building a set of Matrix protocol libraries, and for the "create session object" API to consistently return the same data (whether an access token or login credentials are provided), it's necessary for the library to be able to request the device ID that belongs to a given access token.

This MSC as currently proposed would resolve that problem.

**Comment by richvdh** [comment]
this feels like a bit of a no-brainer to me.

@mscbot fcp merge

**Comment by turt2live** [comment]
sorry, I can't read - this is in FCP not landed yet.

**Comment by turt2live** [comment]
have opened https://github.com/matrix-org/matrix-doc/pull/2738 to land this properly once FCP completes. Apologies for the screwup :(

**Comment by turt2live** [comment]
Merged 🎉

**Pull request merged**
