### PR TITLE
Fix some obsolete uses of user_id key in events

### PR DESCRIPTION
**Pull request by Ralith**
This should account for most of the incorrect users in the client-server API docs. I made no attempt to review the server-server API for similar errors.

### CODE REVIEW

**Comment by richvdh** [comment]
@Ralith: thanks!

Any chance of a [changelog](https://github.com/matrix-org/matrix-doc/blob/master/changelogs/client_server.rst) entry?

**Comment by Ralith** [comment]
Will do tonight.

**Comment by Ralith** [comment]
Added a changelog entry and rebased.

**Comment by richvdh** [comment]
looks great, tyvm

**Pull request merged**
